#!/bin/bash

set -x
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$DIR"

PROJECT_DIR="$DIR/.."

cd ..

rm -rf ./library/classes && mkdir ./library/classes
rm -rf ./generated_classes && mkdir generated_classes

clojure -X membrane.ios/compile-bindings 
clojure -X com.phronemophobic.mobiletest.membrane/compile-interface-class
clojure -X com.phronemophobic.mobiletest.objc/compile-bindings
clojure -X:depstar-membrane

INITIALIZE_AT_BUILD_TIME='clojure,clojure.stacktrace,tech.v3.datatype,sci.impl,babashka.nrepl,babashka.impl,hiccup,org.httpkit,tech.v3.resource,bencode,flatland.ordered,com.phronemophobic,com.phronemophobic.mobiletest,babashka.nrepl.impl,datascript,edamame.impl,tech.v3,tech.v3.parallel,sci.addons,tech.v3.datatype.ffi,sci,primitive_math,primitive_math$unuse_primitive_operators,primitive_math$using_primitive_operators_QMARK_,primitive_math$use_primitive_operators,primitive_math$variadic_predicate_proxy,primitive_math$variadic_proxy,primitive_math$unuse_primitive_operators,primitive_math$using_primitive_operators_QMARK_,primitive_math$use_primitive_operators,primitive_math$variadic_predicate_proxy,primitive_math$variadic_proxy,membrane.example,membrane,com.rpl.specter,riddley,com.rpl'

pushd library

rm -rf ./tmp

$GRAALVM_HOME/bin/native-image \
    --report-unsupported-elements-at-runtime \
    --initialize-at-build-time="$INITIALIZE_AT_BUILD_TIME" \
    '--initialize-at-run-time=org.httpkit.client.ClientSslEngineFactory$SSLHolder' \
    --no-fallback \
    --no-server \
    -H:CompilerBackend=llvm \
    -H:+ExitAfterRelocatableImageWrite \
    -H:+SharedLibrary \
    -H:+AddAllCharsets \
    -H:+ReportExceptionStackTraces \
    -H:-DeadlockWatchdogExitOnTimeout \
    -H:DeadlockWatchdogInterval=0 \
    -H:+RemoveSaturatedTypeFlows \
    -H:-SpawnIsolates \
    -H:PageSize=16384 \
    -Djdk.internal.lambda.eagerlyInitialize=false \
    -H:+ReportExceptionStackTraces \
    -H:TempDirectory="$PROJECT_DIR"/library/tmp \
    -H:ReflectionConfigurationFiles="${PROJECT_DIR}"/conf/reflectionconfig-arm64-ios.json \
    -H:JNIConfigurationFiles="${PROJECT_DIR}"/conf/jniconfig-arm64-ios.json \
    -H:ResourceConfigurationFiles="${PROJECT_DIR}"/conf/resourceconfig-arm64-ios.json \
    -J-Dclojure.spec.skip-macros=true \
    -J-Xmx20G \
    -J-XX:MaxDirectMemorySize=8G \
    -J-Dclojure.compiler.direct-linking=true \
    -J-Dtech.v3.datatype.graal-native=true \
    -Dsvm.targetName=iOS \
    -Dsvm.targetArch=arm64 \
    -H:+UseCAPCache \
    -H:CAPCacheDir="${PROJECT_DIR}"/conf/capcache \
    '-Dsvm.platform=org.graalvm.nativeimage.Platform$IOS_AARCH64' \
    -jar ../target/mobiletest-uber.jar

rm -rf ./build/out
mkdir -p build/out

find ./tmp -name 'llvm.o' -exec cp {} build/out \;
find ./tmp -name 'mobiletest-uber.o' -exec cp {} build/out \;

popd
