#!/bin/bash

set -x
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$DIR"

cd ..

mkdir -p build

pushd build

staticjdk='staticjdk'
target='ios-arm64'
version='18-ea+prep18-8'

fname="${staticjdk}-${target}-gvm-${version}.zip"

if [ ! -f "$fname" ]; then
   curl -O "https://download2.gluonhq.com/substrate/staticjdk/${fname}"
   unzip "$fname"
fi

popd
